### ISSUE TITLE
Update for Minecraft 1.19

### ISSUE THREAD

**Issue by lospejos** [shedaniel/can-i-mine-this-block#16]
Please update to Minecraft 1.19.

In **Minecraft 1.19** with **REI** it produces error log `waila_errors.log`:

```
2022-06-08 - 19:49:27
class me.shedaniel.cimtb.CimtbWailaPlugin
java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2588.method_27692(net.minecraft.class_124)'
at me.shedaniel.cimtb.CimtbWailaPlugin.appendBody(CimtbWailaPlugin.java:49)
at mcp.mobius.waila.hud.ComponentHandler.handleBlock(ComponentHandler.java:62)
at mcp.mobius.waila.hud.ComponentHandler.gatherBlock(ComponentHandler.java:50)
at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:112)
at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:44)
at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:21)
at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
at net.minecraft.class_310.handler$zkl000$onEndTick(class_310.java:4390)
at net.minecraft.class_310.method_1574(class_310.java:1869)
at net.minecraft.class_310.method_1523(class_310.java:1101)
at net.minecraft.class_310.method_1514(class_310.java:734)
at net.minecraft.client.main.Main.main(Main.java:237)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
 

It seems mod should be updated/rebuilt using **Fabric** for **Minecraft 1.19**

**Comment by shedaniel** [comment]
Please do not report version incompatibility as issues, this is not an issue, the mod works for its specified version.

1.19 support will come at a later date.

**Comment by lospejos** [comment]
Sorry for that, and thanks for your reply.
